### ISSUE TITLE
ValueError: tf.function-decorated function tried to create variables on non-first call. While running on Tensorflow 2.0 and above

### ISSUE THREAD

**Issue by rytisss** [koshian2/OctConv-TFKeras#16]
I am getting an error while trying to run the code with the latest Tensorflow (2.0 and above) version. However, workaround is to run code with `tf.config.run_functions_eagerly(True)`. I am not sure, but I suspect that some values are created each time in the `call` method of `OctConv2D` class. Are there any hints on how to overcome the problem? Any help is appreciated :)

**Comment by innat** [comment]
This is because of defining the training layer (`K.conv2d`) inside the `call` method rather than in `init` or `build`. With `tf...eagerly...true`, it's pointless because each it's created `conv2d` layer with new init and model will not generalize.
