### ISSUE TITLE
Can I access your colab notebook?

### ISSUE THREAD

**Issue by ryoppippi** [koshian2/OctConv-TFKeras#2]
I read your awesome article!
Could you share your colab notebook for training?

**Comment by koshian2** [comment]
@ryoppippi 
This is my colab notebook. Plese Use them freely.

**Train OctConv ResNet**
https://colab.research.google.com/drive/1MXN46mhCk6s-G_nfJrH1B6_8GXh-a_QH

**Measuring prediction time**
https://colab.research.google.com/drive/12MdVXyB9K3FnpzYNmyc3qu5s59-53WNE

**Comment by ryoppippi** [comment]
Thank you so much!!
I will try it!!
